"""Markdown report generation."""

from pathlib import Path
from typing import Dict, Any
from datetime import datetime
from .base import get_cost_color


def generate_markdown_report(results: Dict[str, Any], output_path: Path) -> str:
    """Generate markdown report with cost visualizations."""
    summary = results["summary"]
    commits = results["commits"]
    
    # Calculate additional metrics
    model = summary["model"]
    total_cost = summary["total_cost"]
    total_commits = summary["total_commits"]
    avg_cost_per_commit = total_cost / total_commits if total_commits > 0 else 0
    
    # Generate cost chart data
    daily_costs = {}
    for commit in commits:
        date = commit["date"][:10]  # YYYY-MM-DD
        cost = commit["cost"]
        daily_costs[date] = daily_costs.get(date, 0) + cost
    
    # Sort dates
    sorted_dates = sorted(daily_costs.keys())
    
    md_content = f"""# AI Cost Analysis Report

> Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
> Model: `{model}`
> Analysis Mode: {summary.get("mode", "unknown")}

## Summary

| Metric | Value |
|--------|-------|
| **Total Cost** | {summary["total_cost_formatted"]} |
| **Total Commits** | {total_commits} |
| **Average per Commit** | ${avg_cost_per_commit:.4f} |
| **Hours Saved** | {summary["total_hours_saved"]:.1f}h |
| **Value Generated** | ${summary["total_value_generated"]:.2f} |
| **ROI** | {summary["average_roi"]} |

## Cost Visualizations

### Daily Cost Breakdown

```
"""
    
    # Generate ASCII bar chart for daily costs
    if sorted_dates:
        max_cost = max(daily_costs.values())
        chart_width = 40
        
        for date in sorted_dates[-14:]:  # Last 14 days
            cost = daily_costs[date]
            bar_length = int((cost / max_cost) * chart_width) if max_cost > 0 else 0
            bar = "█" * bar_length
            md_content += f"{date} | {bar} ${cost:.4f}\n"
    
    md_content += f"""```

### Cumulative Cost Over Time

```
"""
    
    # Generate cumulative chart
    cumulative = 0
    for date in sorted_dates:
        cumulative += daily_costs[date]
        bar_length = int((cumulative / total_cost) * 30) if total_cost > 0 else 0
        bar = "█" * bar_length
        md_content += f"{date} | {bar} ${cumulative:.4f}\n"
    
    md_content += f"""```

## Recent AI Commits

| Commit | Date | Cost | Message |
|--------|------|------|---------|
"""
    
    # Add last 10 commits
    for c in commits[:10]:
        msg = c["commit_message"][:40].replace("\n", " ").replace("|", "\\|")
        md_content += f"| {c['commit_hash']} | {c['date'][:10]} | {c['cost_formatted']} | {msg} |\n"
    
    md_content += f"""
## Badge

![AI Cost](https://img.shields.io/badge/AI%20Cost-{summary["total_cost_formatted"].replace("$", "%24")}-{get_cost_color(total_cost)})
![Commits](https://img.shields.io/badge/AI%20Commits-{total_commits}-blue)
![Model](https://img.shields.io/badge/Model-{model.replace("/", "%2F")}-lightgrey)

## Configuration

```bash
# To reproduce this analysis
costs analyze --repo . --model {model} --full-history
```

---
*Report generated by [ai-cost-tracker](https://github.com/your-org/ai-cost-tracker)*
"""
    
    # Write to file
    output_path.write_text(md_content)
    return md_content
